version: '2'
services:
  # --------------------------------------------- Web app container
  webapp:
    container_name: homer-webapp
    build: ./webapp/.
    image: sipcapture/homer-webapp
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes:
      - /homer-api/
      - homer-data-semaphore:/homer-semaphore/
    links:
      - "mysql:mysql"
    env_file:
      - ./homer.env
    restart: always
  # --------------------------------------------- cron container
  cron:
    container_name: homer-cron
    build: ./cron/.
    image: sipcapture/homer-cron
    depends_on:
      - mysql
    volumes:
      - homer-data-semaphore:/homer-semaphore/
    links:
      - "mysql:mysql"
    env_file:
      - ./homer.env
    restart: always
  # --------------------------------------------- Kamailio container
  kamailio:
    container_name: homer-kamailio
    build: ./kamailio/.
    image: sipcapture/homer-kamailio
    ports:
      - "9060:9060/udp"
    depends_on:
      - mysql
    links:
      - "mysql:mysql"
    volumes:
      - homer-data-semaphore:/homer-semaphore/
    # entrypoint:
    #   - /bin/bash
    # command:
    #   >
    #   -c 'while true; do sleep 60; done;'
    env_file:
      - ./homer.env
    restart: always
  # --------------------------------------------- Data bootstrapping container
  bootstrap:
    container_name: bootstrap-mysql
    image: mysql:5.6
    depends_on:
      - mysql
      - webapp
    links:
      - "mysql:mysql"
    volumes_from:
      - webapp
    volumes:
      - homer-data-semaphore:/homer-semaphore/
      - ./bootstrap-data/bootstrap.sh:/bootstrap.sh
    # entrypoint:
    #   - /bin/bash
    # command:
    #   >
    #   -c 'while true; do sleep 60; done;'
    entrypoint:
      - /bootstrap.sh
    env_file:
      - ./homer.env
  # --------------------------------------------- MySQL container.
  mysql:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - ./mysql/run.sh:/run.sh
      - homer-data-semaphore:/homer-semaphore/
      - homer-data-mysql:/var/lib/mysql
    entrypoint:
      - /run.sh
    env_file:
      - ./homer.env
    restart: always
volumes:
  homer-data-semaphore:
  homer-data-mysql:
